### PR TITLE
Standard Forms SetSession

### PR DESCRIPTION
**Pull request by chrisbutzke**
## Updates
- Added the event listeners to standard forms ebro/dcga/guide/pepc to set the sessionStorage value. This ungates all the digital guides.
- Autofill the gate forms so the user doesn't have to fill that form out again in the current session. The form cannot be automatically submitted because of recaptcha, but at least it's filled in and validated. We will need to look into recaptcha workaround, update recaptcha version (future maybe?), or remove recaptcha for this function to fully work.
- update standard form validation (kristin identified issue when using autofill)
- removed contact form recaptcha call because it is being called at the end of the page and it wasn't coded correctly to begin with
- update lodash dependency to patch vulnerability
- moved recaptcha aria additions to window load
- IRA check writing js content for sites with the <p> Q/A format

### CODE REVIEW

**Comment by chrisbutzke** [comment]
We can review during standup.

**Comment by melissaanderegg** [comment]
in local testing, contact form on /contact-us page does not direct to /thank-you page

**Comment by melissaanderegg** [comment]
Should IRA check-writing content be added to IRA pages that don't have the syndicated class? example: http://stelterstaging.ingeniuxondemand.com/albion-planmygift/ira-charitable-rollover

**Comment by melissaanderegg** [comment]
These forms do not get auto-populated - should any of these be added? 

- /contact-us form
- have a question form (? widget)
- /gift-intention form

**Pull request merged**
